### ISSUE TITLE
Problem with XML Parse in PRTG Version 22.2.77.2204 

### ISSUE THREAD

**Issue by SyncMasta** [WAdama/nas_pkg_versions#1]
Lookupfile  "C:\Program Files (x86)\PRTG Network Monitor\lookups\custom\prtg.standardlookups.nas.hbintstatus.ovl" can not be loaded (XML Parser mismatch: Wanted , got )

Synology DS218 / DSM 7.1-42661

**Comment by WAdama** [comment]
Why you are using a ovl file of nas_hb_status for this sensor?

This nas_pkg_versions not nas_hb_status...

**Comment by SyncMasta** [comment]
sorry. i also tried your other scripts. 
So it was a mistake above. it is "C:\Program Files (x86)\PRTG Network Monitor\lookups\custom\prtg.standardlookups.nas.packages.ovl"

**Comment by WAdama** [comment]
Hmmm, I'm not sure what the problem might be, but I use the exact same file as it is provided here and I don't get an error...

**Comment by SyncMasta** [comment]
hm also the identic PRTG Version ?

**Comment by WAdama** [comment]
Yes, same version PRTG and Synology DSM.

How did you create the ovl file? Downloaded it or maybe created it by copying from the Github site?

By the way, when do you get the error?

**Comment by SyncMasta** [comment]
download. So right click - save link as

**Comment by SyncMasta** [comment]
Okay, i think that was the problem. 
When i create a new file an copy & paste the sourcecode, the file likes differend and no error occures. 

Thanks for the hint.

**Comment by WAdama** [comment]
You're welcome...

I'm glad it was something easy...

**Comment by SyncMasta** [comment]
Yes, thanks. 
But.... 
i got an error in Sensor: 
XML: Das zurückgelieferte XML entspricht nicht dem erwarteten Schema. (Code: PE233) -- JSON: Das zurückgelieferte JSON entspricht nicht der erwarteten Struktur (Invalid JSON.). (Code: PE231)

May be not correct access rules on synology ?

**Comment by WAdama** [comment]
The user you are working with has admin rights?

Which way do you connect to your Syno via SSH? Certificate or User/Password.

As I described it in the Readme it should work without problems.

**Comment by SyncMasta** [comment]
yes, user is in admin-group.
user/password is used.

**Comment by WAdama** [comment]
What do you get if your running the script manually in SSH window on your Syno?

**Comment by WAdama** [comment]
As there's no answer for days, it seems this can be closed...
